#!/usr/bin/env bash
# Installing nginx on server listen to port 80 an return html single text page

sudo apt-get -y update && sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /usr/share/nginx/html

sudo mkdir -p /var/www/html
sudo chown -R "$USER:$USER" /var/www/html

#sudo cp /etc/nginx/sites-available/default ~/nginx_backup/sites-available/default_backup
block="/etc/nginx/sites-available/default"
sudo tee $block > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}

EOF

#sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html

sudo echo 'Holberton School for the win!' | sudo tee /var/www/html/index.html

#sudo echo 'Holberton School' | sudo tee /usr/share/nginx/html/index.html

sudo nginx -t && sudo service nginx start
