#!/usr/bin/env bash
# install nginx and configure to listen port 80 and server basic html page
sudo apt-get -y update
sudo apt-get install -y nginx nginx-full nginx-common
sudo ufw allow 'Nginx HTTP'
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
