#!/usr/bin/env bash
# Configure location redirection rule
file=/etc/nginx/sites-available/default
has_redirect=$(sudo grep 'redirect_me' $file)
if [ "$has_redirect" == "" ];then
    echo "Reconfiguring to redirect"
    sudo sed -i ':a;N;$!ba;s/\n}/\n    location \/redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n}/g' $file
fi

