#!/usr/bin/env bash
# Configure location redirection rule
sudo apt-get -y update && sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx stop
block="/etc/nginx/sites-available/default"
sudo tee $block > /dev/null <<EOF                                    
server {

    listen 80 default_server;

    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name localhost;

    error_page 404 /custom_404.html;

    location = /custom_404.html {
             root /var/www/html;
             internal;
    }

    location / {

        try_files \$uri \$uri/ =404;

    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}
                                                                    
EOF
echo "Holberton School" > /var/www/html/index.html
echo -e "Ceci n'est pas une page" > /var/www/html/custom_404.html

sudo nginx -t && sudo /etc/init.d/nginx restart
