#!/usr/bin/env bash
# This configures nginx to listen port 80
conf_file='/etc/nginx/sites-available/default'
conf_file2='/etc/nginx/sites-enabled/default'
sudo sed -i 's/8080/80/g' "$conf_file" "$conf_file2"
sudo service nginx start
