#!/usr/bin/env bash
#kill buzz
pgrep -f "4-to_infinity_and_beyond" #| head -1 | cut -d " " -f 5- | xargs | cut -d " " -f1
pid=$( ps aux | grep "4-to" | head -1 | cut -d " " -f 5- | xargs | cut -d " " -f1 )
#echo "$pid"
id=$( ps -o ppid= "$pid" | xargs )
#pkill -15 -P "$id"
