#!/usr/bin/env bash
#Bad luck baby
c=1
while (( c<11 ))
do
    if [ $c -eq 4 ]
    then
	echo "bad luck"
    elif [ $c -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    c=$(( c+1 ))
done
