#!/usr/bin/env bash
#more and more bad luck baby
c=1
while (( c<21 ))
do
    echo "$c"
    case "$c" in
	4) echo "bad luck from China"
	   ;;
	9) echo "bad luck from Japan"
	   ;;
	17) echo "bad luck from Italy"
	   ;;
    esac
    c=$(( c+1 ))
done
