#!/usr/bin/env bash
#Tik tok the time is running baby
hour=0
while (( hour < 13 ))
do
    echo "Hour: ${hour}"
    minute=1
    while (( minute < 60 ))
    do
	echo $minute
	minute=$(( minute + 1 ))
    done
    hour=$(( hour + 1 ))
done
